from enum import Enum


class AuditAction(str, Enum):
    # Admin
    PROMOTE_ADMIN = "PROMOTE_ADMIN"
    DEMOTE_ADMIN = "DEMOTE_ADMIN"

    # Projects
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_DELETED = "PROJECT_DELETED"

    # Membership
    PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED"
    PROJECT_MEMBER_REMOVED = "PROJECT_MEMBER_REMOVED"
    PROJECT_ROLE_UPDATED = "PROJECT_ROLE_UPDATED"

    # Tasks
    TASK_CREATED = "TASK_CREATED"
    TASK_DELETED = "TASK_DELETED"
